version: '3'
services:
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"         # Graphite web interface
      - "2003:2003"     # Graphite plaintext metrics
      - "8125:8125/udp" # StatsD metrics
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"     # Grafana web interface
    restart: always
