hosts: localhost
  become: true
  tasks:
   - name: Run smart-traffic Docker container
     community.docker.docker_container:
       name: smart-traffic
       image: smart-traffic-devops
       state: started
       ports:
         - "9090:8080"
