- hosts: servers
  become: true
  tasks:
    - name: Stop previous container
      shell: docker stop traffic-api && docker rm traffic-api
      ignore_errors: true

    - name: Run latest container
      shell: docker run -d -p 8080:8080 --name traffic-api traffic-api:latest
